server:
  port: 8080

#debug: true

spring:
  application:
    name: GearX
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60000
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  output:
    ansi:
      enabled: ALWAYS
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  folder: ${FOLDER}

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}
  access-exp-minutes: ${JWT_ACCESS_EXP_MINUTES}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    ping:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

mail:
  from:
    email: ${MAIL_FROM_EMAIL:${SMTP_USERNAME}}
    name: ${MAIL_FROM_NAME}

app:
  name: ${APP_NAME}
  base-url: ${APP_BASE_URL}
  otp:
    ttl-seconds: ${OTP_TTL_SECONDS}
    resend-window-seconds: ${OTP_RESEND_WINDOW_SECONDS}
    max-attempts: ${OTP_MAX_ATTEMPTS}

mybatis:
  config-location: classpath:mybatis/configuration/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true